feature_list = [
    'IIS-WebServerRole',
    'IIS-WebServer',
    'IIS-WebServerManagementTools',
    'IIS-ApplicationDevelopment',
    'IIS-ISAPIFilter',
    'IIS-ISAPIExtensions',
    'IIS-NetFxExtensibility',
    'IIS-ASPNET',
    'IIS-CGI',
    'IIS-ClientCertificateMappingAuthentication',
    'IIS-CommonHttpFeatures',
    'IIS-CustomLogging',
    'IIS-DefaultDocument',
    'IIS-DigestAuthentication',
    'IIS-DirectoryBrowsing',
    'IIS-HealthAndDiagnostics',
    'IIS-HostableWebCore',
    'IIS-HttpCompressionDynamic',
    'IIS-HttpCompressionStatic',
    'IIS-HttpErrors',
    'IIS-HttpLogging',
    'IIS-HttpRedirect',
    'IIS-HttpTracing',
    'IIS-IIS6ManagementCompatibility',
    'IIS-IISCertificateMappingAuthentication',
    'IIS-IPSecurity',
    'IIS-Metabase',
    'IIS-WMICompatibility',
    'IIS-LegacyScripts',
    'IIS-LegacySnapIn',
    'IIS-LoggingLibraries',
    'IIS-ManagementConsole',
    'IIS-ManagementScriptingTools',
    'IIS-ManagementService',
    'IIS-ODBCLogging',
    'IIS-Performance',
    'IIS-RequestFiltering',
    'IIS-RequestMonitor',
    'IIS-Security',
    'IIS-ServerSideIncludes',
    'IIS-StaticContent',
    'IIS-URLAuthorization',
    'IIS-WebDAV',
    'IIS-WindowsAuthentication',
    'WAS-WindowsActivationService',
    'WAS-ConfigurationAPI',
    'WAS-NetFxEnvironment',
    'WAS-ProcessModel'
  ]

feature_list.each do |feature|
  windows_feature feature do
    action :install
  end
end
